services:

  my_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Notes-With_Autocorrector
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: db
    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD 
      - POSTGRES_USER=$DATABASE_USER